blank_issues_enabled: false

contact_links:
  - name: 📃 User Documentation
    url: https://docs.gingerwallet.io/
    about: Search the official Ginger Wallet documentation.

  - name: 💬 Community Support
    url: https://github.com/GingerPrivacy/GingerWallet/discussions/categories/support
    about: Ask usage or troubleshooting questions here.

  - name: ❓ Other Question or Idea
    url: https://github.com/GingerPrivacy/GingerWallet/discussions
    about: Search or start a discussion before opening a new issue.
